#!/bin/bash

set -e

root=$(dirname $(readlink -f $0))
pushd $root

images="base python gateway hello haskell pick"

for image in $images; do
    cp images/Dockerfile_${image} ./Dockerfile
    docker build -t klacz/${image} .
    rm Dockerfile
done

popd
