# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='persistent.proto',
  package='Persistent.Proto',
  serialized_pb='\n\x10persistent.proto\x12\x10Persistent.Proto\" \n\x04Term\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\"V\n\x05\x45ntry\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x12\n\ndate_added\x18\x04 \x01(\t\x12\x0f\n\x07term_id\x18\x05 \x01(\x03\"!\n\x11\x43reateTermRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\":\n\x12\x43reateTermResponse\x12$\n\x04term\x18\x01 \x01(\x0b\x32\x16.Persistent.Proto.Term\"\x1e\n\x0eGetTermRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"7\n\x0fGetTermResponse\x12$\n\x04term\x18\x01 \x01(\x0b\x32\x16.Persistent.Proto.Term\"X\n\x12\x43reateEntryRequest\x12$\n\x04term\x18\x01 \x01(\x0b\x32\x16.Persistent.Proto.Term\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"=\n\x13\x43reateEntryResponse\x12&\n\x05\x65ntry\x18\x01 \x01(\x0b\x32\x17.Persistent.Proto.Entry\"9\n\x11GetEntriesRequest\x12$\n\x04term\x18\x01 \x01(\x0b\x32\x16.Persistent.Proto.Term\">\n\x12GetEntriesResponse\x12(\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x17.Persistent.Proto.Entry2\xf1\x02\n\x11PersistentService\x12W\n\nCreateTerm\x12#.Persistent.Proto.CreateTermRequest\x1a$.Persistent.Proto.CreateTermResponse\x12N\n\x07GetTerm\x12 .Persistent.Proto.GetTermRequest\x1a!.Persistent.Proto.GetTermResponse\x12Z\n\x0b\x43reateEntry\x12$.Persistent.Proto.CreateEntryRequest\x1a%.Persistent.Proto.CreateEntryResponse\x12W\n\nGetEntries\x12#.Persistent.Proto.GetEntriesRequest\x1a$.Persistent.Proto.GetEntriesResponse')




_TERM = _descriptor.Descriptor(
  name='Term',
  full_name='Persistent.Proto.Term',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Persistent.Proto.Term.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Persistent.Proto.Term.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=70,
)


_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='Persistent.Proto.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Persistent.Proto.Entry.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='author', full_name='Persistent.Proto.Entry.author', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='Persistent.Proto.Entry.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date_added', full_name='Persistent.Proto.Entry.date_added', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='term_id', full_name='Persistent.Proto.Entry.term_id', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=72,
  serialized_end=158,
)


_CREATETERMREQUEST = _descriptor.Descriptor(
  name='CreateTermRequest',
  full_name='Persistent.Proto.CreateTermRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Persistent.Proto.CreateTermRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=160,
  serialized_end=193,
)


_CREATETERMRESPONSE = _descriptor.Descriptor(
  name='CreateTermResponse',
  full_name='Persistent.Proto.CreateTermResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='Persistent.Proto.CreateTermResponse.term', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=195,
  serialized_end=253,
)


_GETTERMREQUEST = _descriptor.Descriptor(
  name='GetTermRequest',
  full_name='Persistent.Proto.GetTermRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Persistent.Proto.GetTermRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=255,
  serialized_end=285,
)


_GETTERMRESPONSE = _descriptor.Descriptor(
  name='GetTermResponse',
  full_name='Persistent.Proto.GetTermResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='Persistent.Proto.GetTermResponse.term', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=287,
  serialized_end=342,
)


_CREATEENTRYREQUEST = _descriptor.Descriptor(
  name='CreateEntryRequest',
  full_name='Persistent.Proto.CreateEntryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='Persistent.Proto.CreateEntryRequest.term', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='author', full_name='Persistent.Proto.CreateEntryRequest.author', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='Persistent.Proto.CreateEntryRequest.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=344,
  serialized_end=432,
)


_CREATEENTRYRESPONSE = _descriptor.Descriptor(
  name='CreateEntryResponse',
  full_name='Persistent.Proto.CreateEntryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry', full_name='Persistent.Proto.CreateEntryResponse.entry', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=434,
  serialized_end=495,
)


_GETENTRIESREQUEST = _descriptor.Descriptor(
  name='GetEntriesRequest',
  full_name='Persistent.Proto.GetEntriesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='Persistent.Proto.GetEntriesRequest.term', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=497,
  serialized_end=554,
)


_GETENTRIESRESPONSE = _descriptor.Descriptor(
  name='GetEntriesResponse',
  full_name='Persistent.Proto.GetEntriesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='Persistent.Proto.GetEntriesResponse.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=556,
  serialized_end=618,
)

_CREATETERMRESPONSE.fields_by_name['term'].message_type = _TERM
_GETTERMRESPONSE.fields_by_name['term'].message_type = _TERM
_CREATEENTRYREQUEST.fields_by_name['term'].message_type = _TERM
_CREATEENTRYRESPONSE.fields_by_name['entry'].message_type = _ENTRY
_GETENTRIESREQUEST.fields_by_name['term'].message_type = _TERM
_GETENTRIESRESPONSE.fields_by_name['entries'].message_type = _ENTRY
DESCRIPTOR.message_types_by_name['Term'] = _TERM
DESCRIPTOR.message_types_by_name['Entry'] = _ENTRY
DESCRIPTOR.message_types_by_name['CreateTermRequest'] = _CREATETERMREQUEST
DESCRIPTOR.message_types_by_name['CreateTermResponse'] = _CREATETERMRESPONSE
DESCRIPTOR.message_types_by_name['GetTermRequest'] = _GETTERMREQUEST
DESCRIPTOR.message_types_by_name['GetTermResponse'] = _GETTERMRESPONSE
DESCRIPTOR.message_types_by_name['CreateEntryRequest'] = _CREATEENTRYREQUEST
DESCRIPTOR.message_types_by_name['CreateEntryResponse'] = _CREATEENTRYRESPONSE
DESCRIPTOR.message_types_by_name['GetEntriesRequest'] = _GETENTRIESREQUEST
DESCRIPTOR.message_types_by_name['GetEntriesResponse'] = _GETENTRIESRESPONSE

class Term(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TERM

  # @@protoc_insertion_point(class_scope:Persistent.Proto.Term)

class Entry(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENTRY

  # @@protoc_insertion_point(class_scope:Persistent.Proto.Entry)

class CreateTermRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATETERMREQUEST

  # @@protoc_insertion_point(class_scope:Persistent.Proto.CreateTermRequest)

class CreateTermResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATETERMRESPONSE

  # @@protoc_insertion_point(class_scope:Persistent.Proto.CreateTermResponse)

class GetTermRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETTERMREQUEST

  # @@protoc_insertion_point(class_scope:Persistent.Proto.GetTermRequest)

class GetTermResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETTERMRESPONSE

  # @@protoc_insertion_point(class_scope:Persistent.Proto.GetTermResponse)

class CreateEntryRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATEENTRYREQUEST

  # @@protoc_insertion_point(class_scope:Persistent.Proto.CreateEntryRequest)

class CreateEntryResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATEENTRYRESPONSE

  # @@protoc_insertion_point(class_scope:Persistent.Proto.CreateEntryResponse)

class GetEntriesRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETENTRIESREQUEST

  # @@protoc_insertion_point(class_scope:Persistent.Proto.GetEntriesRequest)

class GetEntriesResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETENTRIESRESPONSE

  # @@protoc_insertion_point(class_scope:Persistent.Proto.GetEntriesResponse)


# @@protoc_insertion_point(module_scope)
