FROM klacz/haskell

RUN apt-get -y update  \
    && apt-get -y install supervisor

env PATH=/opt/ghc/7.8.3/bin:/opt/cabal/1.20/bin:${PATH}
RUN cabal-1.20 update
RUN cabal-1.20 install --ghc-option=-j4 amqp uuid --global

ADD modules/pick /srv/klaczng/pick
WORKDIR /srv/klaczng/pick

RUN mkdir /tmp/pick-build
RUN cabal-1.20 configure --builddir=/tmp/pick-build \
    && cabal-1.20 install --builddir=/tmp/pick-build --prefix /opt/klaczng/pick

USER klaczng
