FROM klacz/base

RUN apt-get -y update  \
    && apt-get -y install software-properties-common

RUN apt-add-repository "deb http://ppa.launchpad.net/hvr/ghc/ubuntu precise main" \
    && apt-get -y update

RUN apt-get install -y --force-yes \
    ghc-7.8.3 \
    cabal-install-1.20 \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*
