#!/usr/bin/env python2

import os
import sys
import uuid

# add lib/python to path
module_dir = os.path.dirname(os.path.abspath(__file__))
root_dir = os.path.dirname(os.path.dirname(module_dir))
lib_dir = os.path.sep.join((root_dir, 'lib', 'python'))
sys.path.insert(0, lib_dir)


import hello
from klaczng import utils


def target(uri):
    t = hello.Hello(uri)
    queue = str(uuid.uuid4())
    t.exchange_declare('topic', 'events')
    t.queue_bind(queue, 'events', 'klacz.privmsg.hello')
    t.start_recieving(queue)


module = utils.KlaczNGModule('hello', target)
module.run()
