#!/usr/bin/env python2

import os
import sys
import uuid

import argparse


# add lib/python to path
module_dir = os.path.dirname(os.path.abspath(__file__))
root_dir = os.path.dirname(os.path.dirname(module_dir))
lib_dir = os.path.sep.join((root_dir, 'lib', 'python'))
sys.path.insert(0, lib_dir)


import hello


parser = argparse.ArgumentParser()
parser.add_argument('-u', '--uri', default='amqp://127.0.0.1:5672/',
                    help="AMQP host URI")
args = parser.parse_args()


if __name__ == '__main__':
    t = hello.Hello(args.uri)
    queue = str(uuid.uuid4())
    t.queue_bind(queue, 'events', 'klacz.privmsg.hello')
    t.start_recieving(queue)
