#!/usr/bin/env python2

import os
import sys
import uuid


# TODO: fix this hack
# This adds the parent dir to the PYTHONPATH
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


from klaczng.modules import hello


if __name__ == '__main__':
    t = hello.Hello()
    queue = str(uuid.uuid4())
    t.queue_bind(queue, 'events', 'klacz.privmsg.hello')
    t.start_recieving(queue)
